#!/bin/sh

set -eu

# Exit with success if running inside live-build.
if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
  exit 0
fi

CMD=/usr/local/lib/additional-software/asp-handle-package-changes
# Use a unique unit name, so that we can run multiple instances of the
# hook in parallel.
UUID=$(cat /proc/sys/kernel/random/uuid)
UNIT=tails-additional-software-post-apt-hook-${UUID}
systemd-run --unit="${UNIT}" "${CMD}" "$@"
