#!/bin/sh

set -e
set -u

echo "Installing Flatpak apps"

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --assumeyes --noninteractive flathub org.signal.Signal
