#!/bin/sh

set -eu
set -x

echo "Compiling and installing arti"

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

trap_handler() {
    if [ "${SUCCESS:-}" != yes ]; then
        sh -i
    fi
}

trap trap_handler EXIT

# XXX: we should enable trixie in our Debian snapshots infra instead
# of this ugly hack
# We need rustc >= 1.65 to compile Arti, but it is not in Debian
# bookworm
echo "deb http://ftp.us.debian.org/debian/ trixie main" \
     > /etc/apt/sources.list.d/trixie.list
apt update
apt install --yes rustc/trixie gcc-13-base/trixie libllvm16/trixie \
                  libstdc++6/trixie libzstd1/trixie

ensure_hook_dependency_is_installed cargo libsqlite3-dev libssl-dev pkgconf


# By default DNS is set up to use Tor, which we aren't running at
# build time. So let's use OpenDNS temporarily.
mv /etc/resolv.conf /etc/resolv.conf.orig
echo 'nameserver 208.67.220.220' > /etc/resolv.conf

cd /usr/src
# We do not use the torsocks git-wrapper during build time
/usr/bin/git clone 'https://gitlab.torproject.org/tpo/core/arti/'
cd arti
LATEST_VERSION_TAG="$(git tag | grep ^arti-v | sort --version-sort | tail -n1)"
(
    export GNUPGHOME="$(mktemp -d)"
    # Import nickm's key who has signed all releases so far
    curl --noproxy '*' 'https://keys.openpgp.org/vks/v1/by-fingerprint/2133BC600AB133E1D826D173FE43009C4607B1FB' | gpg --import
    git tag --verify "${LATEST_VERSION_TAG}"
    rm -rf "${GNUPGHOME}"
)
git checkout "${LATEST_VERSION_TAG}"
cargo build -p arti --release
mv target/release/arti /usr/bin
cd ..
rm -rf arti /root/.cargo

# Restore DNS
mv /etc/resolv.conf.orig /etc/resolv.conf

# We don't need trixie or any of the packages we installed from it any
# more after we're done compiling
rm /etc/apt/sources.list.d/trixie.list
apt update
apt install --purge --yes --allow-downgrades libstdc++6/bookworm libzstd1/bookworm
apt purge --yes gcc-13-base

addgroup --system --quiet arti
adduser --system --quiet --no-create-home arti
chown -R arti:arti /etc/arti/
mkdir -p /var/lib/arti/cache /var/lib/arti/state
chown -R arti:arti /var/lib/arti

SUCCESS=yes
