#!/bin/sh

set -eu

echo "Copying WhisperBack and documentation launchers to the desktop"

APPS="tails-documentation whisperback"

mkdir --parents /etc/skel/Desktop

for app in $APPS; do
    install \
	--mode=0755 \
	"/usr/share/applications/${app}.desktop" \
	/etc/skel/Desktop/
done
