#!/bin/sh

set -e

echo 'Updating thunderbird.desktop'
sed -i --regexp-extended \
    's;^Exec=\S+;Exec=/usr/local/bin/thunderbird;' \
    /usr/share/applications/thunderbird.desktop

# The desktop entry must match the application name in the .flatpak-info
# file.
mv /usr/share/applications/thunderbird.desktop /usr/share/applications/org.mozilla.Thunderbird.desktop
