#!/bin/sh

set -e

echo 'Updating thunderbird.desktop'
sed -i --regexp-extended \
    's;^Exec=\S+;Exec=/usr/local/bin/thunderbird;' \
    /usr/share/applications/thunderbird.desktop

# There must be a desktop entry with a filename which matches the
# application name in the .flatpak-info file.
ln -s thunderbird.desktop /usr/share/applications/org.mozilla.Thunderbird.desktop
