#!/bin/bash

set -eu
set -x

# This script rebuilds the org.boum.tails.Platform flatpak runtime

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GIT_TOPLEVEL_DIR=$(git rev-parse --show-toplevel)
TARGET_DIR="${GIT_TOPLEVEL_DIR}/config/chroot_local-includes/var/lib/flatpak/runtime/org.boum.tails.Platform"

# We didn't find a way to make flatpak install to a custom
# directory directly, so we install to the default user installation
# directory first and move it to the git repo
RUNTIME_DIR=${HOME}/.local/share/flatpak/runtime/org.boum.tails.Platform

BUILD_DIR="${DIR}/build-dir"
REPO_DIR="${DIR}/repo"

# Check that the working tree is clean, because we automatically commit
# the changes to the flatpak app to the git repo and we don't want to
# commit other uncommitted changes.
# Check that the working tree is clean (at least in `$TARGET_DIR)`, because we automatically commit
# the changes to the flatpak app to the git repo and we don't want to
# commit other uncommitted changes.
if [ -n "$(git status --porcelain "${TARGET_DIR}")" ]; then
    echo >&2 "Error: The working tree has uncommitted changes."
    exit 1
fi

# Create a new OSTree repository
rm -rf "${REPO_DIR}"
ostree init --mode archive-z2 --repo="${REPO_DIR}"

# Export the runtime to the OSTree repository
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"/{export,files,usr}
cp "${DIR}/metadata" "${BUILD_DIR}"
flatpak build-export "${REPO_DIR}" "${BUILD_DIR}" stable

# Install the runtime from the OSTree repository
if flatpak --user remote-ls --runtime platform-origin > /dev/null 2>&1; then
    flatpak --user remote-delete --force platform-origin
fi
flatpak remote-add --user --no-gpg-verify platform-origin "${REPO_DIR}"
flatpak install --reinstall -y platform-origin org.boum.tails.Platform

# Remove the existing runtime from the git repo
rm -rf "${TARGET_DIR}"

# Copy the runtime to the git repo
cp -a "${RUNTIME_DIR}" "${TARGET_DIR}"

# Commit the changes to the git repo
git add "${TARGET_DIR}"
git commit -m "Rebuild org.boum.tails.Platform flatpak runtime"
git show
